import NavBar from "@/components/NavBar";
import "./globals.css";
import { Inter, IBM_Plex_Mono } from "next/font/google";
import Background from "@/components/Background";

const inter = Inter({ subsets: ["latin"] });
const IbmPlexMono = IBM_Plex_Mono({
    weight: ["100", "200", "300", "400", "500"],
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={IbmPlexMono.className}>
                {/* <NavBar /> */}
                <main className="pt-24">
                    <section className="container mx-auto px-80 mb-52">{children}</section>
                </main>
            </body>
        </html>
    );
}
